server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres
    url: postgres://nsewcarhphrmqm:f42243b234153f9fa11249bcf826592307088c90df6472c5c780950d5e296e2d@ec2-34-202-54-225.compute-1.amazonaws.com:5432/deu9osbd9vcbcu
    #username: postgres
    username: nsewcarhphrmqm
    #password: 123456
    password: f42243b234153f9fa11249bcf826592307088c90df6472c5c780950d5e296e2d
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
